[package]
name = "glfw-app"
version = "0.1.0"
edition = "2021"

[dependencies]
gl = "0.14.0"
glcall_macro = { path = "glcall_macro" }
stb_image = "0.2.5"

[dependencies.glfw]
version = "*"
default-features = false

[features]
console = []
